[package]
name = "boom_bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" ] }
