name: Deploy

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:

    runs-on: ubuntu-20.04

    steps:
    - name: Clone, build, and run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          tmux kill-session -t boombot_session
          cd ${{ secrets.DEPLOY_HOME }}
          export DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}"
          git pull
          cargo build --release
          python3 handle_migrations.py
          tmux new-session -d -s boombot_session 'cargo run'
          
